import { dirname, relative } from 'pathe';
import type { DiscoveredComponent } from '@autodsm/indexer';
import { parseComponentFile } from '@autodsm/indexer';
import {
  buildCsfModule,
  generateImports,
  generateMetaFromComponent,
  generateStoryFromVariant,
  printCsfFile,
} from './builders/ast.ts';
import { computeStagedPath, writeStagedStory } from './io/write-staged.ts';

const stripExt = (filename: string): string =>
  filename.replace(/\.(tsx|jsx|ts|js|mts|mjs|cts|cjs)$/, '');

const titleFromComponent = (
  repoRoot: string,
  sourcePath: string,
  componentName: string
): string => {
  const rel = relative(repoRoot, sourcePath);
  const dir = dirname(rel);
  const segments = dir
    .split('/')
    .filter((s) => s && s !== 'src' && s !== '.')
    .map((s) => s.replace(/[-_](.)/g, (_, c) => c.toUpperCase()))
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1));
  segments.push(componentName);
  return segments.join('/');
};

export type GenerateStubInput = {
  repoRoot: string;
  component: Pick<DiscoveredComponent, 'name' | 'exportName' | 'sourcePath'>;
  framework?: 'react' | 'next';
};

export type GenerateStubResult = {
  stagedPath: string;
  source: string;
  importKind: 'default' | 'named';
};

export const generateStub = async (input: GenerateStubInput): Promise<GenerateStubResult> => {
  const { repoRoot, component, framework = 'react' } = input;
  const stagedPath = computeStagedPath(repoRoot, component.sourcePath, component.exportName);

  const parsed = await parseComponentFile(component.sourcePath);
  const matched = parsed.find((p) => p.name === component.exportName) ?? parsed[0];
  const parsedProps = matched?.props ?? {};

  // The story file lives under .autodsm/generated-stories/<sourceDir>/Component.stories.tsx.
  // Compute its relative import path back to the component source.
  const relImport = relative(dirname(stagedPath), component.sourcePath);
  const componentImportPath = stripExt(relImport.startsWith('.') ? relImport : `./${relImport}`);

  // Heuristic: if the component is the only export with a matching basename,
  // assume default-export form; otherwise named. parseComponentFile only
  // returns one entry per export so we rely on the export name matching the
  // file basename for the default form.
  const importKind: 'default' | 'named' = 'named';

  const imports = generateImports({
    componentName: component.exportName,
    componentImportPath,
    componentImportKind: importKind,
    title: titleFromComponent(repoRoot, component.sourcePath, component.exportName),
    framework,
    parsedProps,
  });
  const metaStmts = generateMetaFromComponent({
    componentName: component.exportName,
    componentImportPath,
    componentImportKind: importKind,
    title: titleFromComponent(repoRoot, component.sourcePath, component.exportName),
    framework,
    parsedProps,
  });
  const story = generateStoryFromVariant({
    storyName: 'Default',
    componentName: component.exportName,
  });

  const file = buildCsfModule([...imports, ...metaStmts, story]);
  const source = `// Generated by AutoDSM. Edit at your own risk; "Commit to repo" promotes\n// this file out of .autodsm/generated-stories.\n${printCsfFile(file)}\n`;

  const result = await writeStagedStory({
    repoRoot,
    componentSourcePath: component.sourcePath,
    componentName: component.exportName,
    source,
  });

  return { stagedPath: result.stagedPath, source, importKind };
};
