import { dirname, relative } from 'pathe';
import type { types as t } from 'storybook/internal/babel';
import type { DiscoveredComponent } from '@autodsm/indexer';
import { parseComponentFile } from '@autodsm/indexer';
import {
  buildCsfModule,
  generateImports,
  generateMetaFromComponent,
  generateStoryFromVariant,
  printCsfFile,
} from './builders/ast.ts';
import { computeStagedPath, writeStagedStory } from './io/write-staged.ts';
import { buildNextParameters, detectNextRouterMode } from './decorators/next.ts';
import {
  buildProviderDecoratorEntry,
  buildProviderImport,
  detectProvider,
} from './decorators/react.ts';

const stripExt = (filename: string): string =>
  filename.replace(/\.(tsx|jsx|ts|js|mts|mjs|cts|cjs)$/, '');

const titleFromComponent = (
  repoRoot: string,
  sourcePath: string,
  componentName: string
): string => {
  const rel = relative(repoRoot, sourcePath);
  const dir = dirname(rel);
  const segments = dir
    .split('/')
    .filter((s) => s && s !== 'src' && s !== '.')
    .map((s) => s.replace(/[-_](.)/g, (_, c) => c.toUpperCase()))
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1));
  segments.push(componentName);
  return segments.join('/');
};

export type GenerateStubInput = {
  repoRoot: string;
  component: Pick<DiscoveredComponent, 'name' | 'exportName' | 'sourcePath'>;
  framework?: 'react' | 'next';
};

export type GenerateStubResult = {
  stagedPath: string;
  source: string;
  importKind: 'default' | 'named';
  decoratorsApplied: string[];
};

export const generateStub = async (input: GenerateStubInput): Promise<GenerateStubResult> => {
  const { repoRoot, component, framework = 'react' } = input;
  const stagedPath = computeStagedPath(repoRoot, component.sourcePath, component.exportName);

  const parsed = await parseComponentFile(component.sourcePath);
  const matched = parsed.find((p) => p.name === component.exportName) ?? parsed[0];
  const parsedProps = matched?.props ?? {};

  const relImport = relative(dirname(stagedPath), component.sourcePath);
  const componentImportPath = stripExt(relImport.startsWith('.') ? relImport : `./${relImport}`);
  const importKind: 'default' | 'named' = 'named';

  const extraImports: t.ImportDeclaration[] = [];
  const extraParameters: t.ObjectProperty[] = [];
  const decorators: t.Expression[] = [];
  const decoratorsApplied: string[] = [];

  // Next.js-aware metadata: appDirectory hint for the @storybook/nextjs
  // framework so its router/navigation/headers/cache mocks pick the right
  // shape.
  if (framework === 'next') {
    const mode = await detectNextRouterMode(component.sourcePath);
    extraParameters.push(buildNextParameters(mode));
    decoratorsApplied.push(`nextjs:${mode}`);
  }

  // Provider detection: if a Providers component is colocated in a typical
  // location, wrap each story in it via a decorator.
  const provider = await detectProvider(repoRoot);
  if (provider) {
    extraImports.push(buildProviderImport(provider, stagedPath, repoRoot));
    decorators.push(buildProviderDecoratorEntry(provider.exportName));
    decoratorsApplied.push(`provider:${provider.exportName}`);
  }

  const metaInput = {
    componentName: component.exportName,
    componentImportPath,
    componentImportKind: importKind,
    title: titleFromComponent(repoRoot, component.sourcePath, component.exportName),
    framework,
    parsedProps,
    extraParameters,
    decorators,
  };
  const imports = generateImports(metaInput);
  const metaStmts = generateMetaFromComponent(metaInput);
  const story = generateStoryFromVariant({
    storyName: 'Default',
    componentName: component.exportName,
  });

  const file = buildCsfModule([...imports, ...extraImports, ...metaStmts, story]);
  const source = `// Generated by AutoDSM. Edit at your own risk; "Commit to repo" promotes\n// this file out of .autodsm/generated-stories.\n${printCsfFile(file)}\n`;

  const result = await writeStagedStory({
    repoRoot,
    componentSourcePath: component.sourcePath,
    componentName: component.exportName,
    source,
  });

  return {
    stagedPath: result.stagedPath,
    source,
    importKind,
    decoratorsApplied,
  };
};
